# Generated by Django 5.2.10 on 2026-01-30 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('murid-basic', 'Murid Basic'), ('murid-premium', 'Murid Premium'), ('chef', 'Chef')], default='murid-basic', max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('telp', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Harus diisi dengan nomor telepon yang valid. Contoh: +628123456789 (IDN)', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('bio', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
