# Generated by Django 5.2.10 on 2026-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
