# Generated by Django 5.2.10 on 2026-01-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_create_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
