# Generated by Django 5.2.10 on 2026-01-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_create_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
