# Generated by Django 5.2.10 on 2026-02-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_create_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_user',
            old_name='namaLengkap',
            new_name='namaDepan',
        ),
        migrations.AddField(
            model_name='create_user',
            name='namaBelakang',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
