# Generated by Django 5.2.10 on 2026-02-01 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_rename_namalengkap_create_user_namadepan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_user',
            name='dataJoin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
