# Generated by Django 5.2.10 on 2026-02-02 07:01

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_create_user_datajoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_user',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='create_user',
            name='endTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_user',
            name='kelas',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='create_user',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 2, 7, 1, 32, 262733, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
