# Generated by Django 5.2.10 on 2026-02-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_create_user_duration_create_user_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_user',
            name='sertifikasi',
            field=models.FileField(blank=True, null=True, upload_to='sertifikat/'),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='kelas',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
