# Generated by Django 5.2.10 on 2026-02-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_create_user_sertifikasi_alter_create_user_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='kelas',
            field=models.CharField(blank=True, default=1, max_length=20),
        ),
    ]
