# Generated by Django 5.2.10 on 2026-02-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_create_user_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='kelas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
