# Generated by Django 5.2.10 on 2026-02-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_create_user_kelas'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='sertifikasi',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='startTime',
        ),
        migrations.AddField(
            model_name='create_user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='create_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='create_user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='create_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='create_user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='create_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='create_user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='kelas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='role',
            field=models.CharField(default='murid-basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='status',
            field=models.CharField(default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='telp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
