# Generated by Django 5.2.10 on 2026-02-02 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_remove_create_user_bio_remove_create_user_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='create_user',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='create_user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='create_user',
            name='total_detik_online',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='kelas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('murid-basic', 'Murid Basic'), ('murid-premium', 'Murid Premium'), ('chef', 'Chef')], default='murid-basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='telp',
            field=models.CharField(default=' ', max_length=15, validators=[django.core.validators.RegexValidator(message='Format: +628123456789', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
