# Generated by Django 5.2.10 on 2026-02-03 03:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_remove_create_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='kelas',
        ),
        migrations.AlterField(
            model_name='create_user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('murid', 'Murid'), ('chef', 'Chef')], default='murid', max_length=20),
        ),
        migrations.AlterField(
            model_name='create_user',
            name='status',
            field=models.CharField(default='offline', max_length=10),
        ),
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(max_length=16, unique=True)),
                ('foto_ktp', models.ImageField(upload_to='chef/verifikasi/')),
                ('file_cv', models.FileField(upload_to='chef/cv/')),
                ('pendidikan_json', models.JSONField(blank=True, default=list)),
                ('spesialisasi_json', models.JSONField(blank=True, default=list)),
                ('riwayat_kerja_json', models.JSONField(blank=True, default=list)),
                ('rating_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_murid', models.PositiveIntegerField(default=0)),
                ('link_sosmed', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to='administration.create_user')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(upload_to='kelas/thumbnails/')),
                ('deskripsi_singkat', models.TextField(max_length=500)),
                ('deskripsi_lengkap', models.TextField()),
                ('kategori', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('kurikulum_json', models.JSONField(blank=True, default=list)),
                ('tanggal_mulai', models.DateField(default=django.utils.timezone.now)),
                ('total_durasi_jam', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_diajar', to='administration.chefprofile')),
            ],
        ),
        migrations.CreateModel(
            name='murid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riwayat_belajar_json', models.JSONField(blank=True, default=list)),
                ('sertifikat_koleksi', models.JSONField(blank=True, default=list)),
                ('poin_belajar', models.PositiveIntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='murid_profile', to='administration.create_user')),
            ],
        ),
    ]
