# Generated by Django 5.2.10 on 2026-02-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_remove_create_user_bio_remove_create_user_kelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='BasicPremium',
            field=models.BooleanField(default=False),
        ),
    ]
