# Generated by Django 5.2.10 on 2026-02-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_kelas_basicpremium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='deskripsi_singkat',
            new_name='deskripsi',
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='pendapatan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kelas',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
